CREATE TABLE "mytable" (
  "-- 1. PATIENT" text
);

INSERT INTO "mytable" ("-- 1. PATIENT")
VALUES
('CREATE TABLE patient ('),
('patient_id                              VARCHAR(64)    PRIMARY KEY'),
('subtype                                 VARCHAR(64)'),
('cancer_type_acronym                     VARCHAR(32)'),
('other_patient_id                        VARCHAR(64)'),
('age                                     FLOAT'),
('sex                                     VARCHAR(16)'),
('ethnicity                               VARCHAR(64)'),
('race                                    VARCHAR(64)'),
('ajcc_pathologic_tumor_stage             VARCHAR(32)'),
('ajcc_staging_edition                    VARCHAR(16)'),
('path_t_stage                            VARCHAR(16)'),
('path_n_stage                            VARCHAR(16)'),
('path_m_stage                            VARCHAR(16)'),
('os_status                               VARCHAR(32)'),
('os_months                               FLOAT'),
('os_status_flag                          TINYINT'),
('dss_status                              VARCHAR(32)'),
('dss_months                              FLOAT'),
('dss_status_flag                         TINYINT'),
('dfs_status                              VARCHAR(32)'),
('dfs_months                              FLOAT'),
('dfs_status_flag                         TINYINT'),
('pfs_status                              VARCHAR(32)'),
('pfs_months                              FLOAT'),
('pfs_status_flag                         TINYINT'),
('person_neoplasm_cancer_status           VARCHAR(64)'),
('new_tumor_event_after_initial_treatment VARCHAR(16)'),
('radiation_therapy                       VARCHAR(16)'),
('weight                                  FLOAT'),
('icd_10                                  VARCHAR(16)'),
('icd_o_3_histology                       VARCHAR(16)'),
('icd_o_3_site                            VARCHAR(16)'),
('prior_dx                                VARCHAR(16)'),
('in_pancanpathways_freeze                VARCHAR(16)'),
('days_last_followup                      FLOAT'),
('days_to_birth                           FLOAT'),
('days_to_initial_pathologic_diagnosis    FLOAT'),
('genetic_ancestry_label                  VARCHAR(32)'),
('form_completion_date                    VARCHAR(32)'),
('history_neoadjuvant_trtyn               VARCHAR(16)'),
('informed_consent_verified               VARCHAR(16)'),
('primary_lymph_node_presentation_assessment VARCHAR(64)'),
(');'),
('-- 2. SAMPLE'),
('CREATE TABLE sample ('),
('sample_id                               VARCHAR(64)    PRIMARY KEY'),
('patient_id                              VARCHAR(64)'),
('oncotree_code                           VARCHAR(32)'),
('cancer_type                             VARCHAR(64)'),
('cancer_type_detailed                    VARCHAR(128)'),
('tumor_type                              VARCHAR(32)'),
('grade                                   VARCHAR(16)'),
('sample_type                             VARCHAR(32)'),
('tumor_tissue_site                       VARCHAR(64)'),
('tissue_source_site                      VARCHAR(128)'),
('tissue_source_site_code                 VARCHAR(16)'),
('somatic_status                          VARCHAR(32)'),
('tmb_nonsynonymous                       FLOAT'),
('msi_score_mantis                        FLOAT'),
('msi_sensor_score                        FLOAT'),
('aneuploidy_score                        FLOAT'),
('tbl_score                               FLOAT'),
('tissue_prospective_collection_indicator VARCHAR(16)'),
('tissue_retrospective_collection_indicator VARCHAR(16)'),
('FOREIGN KEY (patient_id) REFERENCES patient(patient_id)'),
(');'),
('-- 3. GENE REFERENCE'),
('CREATE TABLE gene_reference ('),
('entrez_gene_id  BIGINT         PRIMARY KEY'),
('hugo_symbol     VARCHAR(64)'),
('cytoband        VARCHAR(32)'),
('gene_type       VARCHAR(64)'),
('INDEX idx_hugo (hugo_symbol)'),
(');'),
('-- 4. MRNA EXPRESSION (raw RSEM)'),
('CREATE TABLE mrna_expression ('),
('hugo_symbol     VARCHAR(64)'),
('entrez_gene_id  BIGINT'),
('sample_id       VARCHAR(64)'),
('rsem_value      DOUBLE'),
('PRIMARY KEY (hugo_symbol'),
('INDEX idx_sample (sample_id)'),
('INDEX idx_gene   (hugo_symbol)'),
(');'),
('-- 5. MRNA ZSCORE — all samples'),
('CREATE TABLE mrna_zscore_all ('),
('hugo_symbol     VARCHAR(64)'),
('entrez_gene_id  BIGINT'),
('sample_id       VARCHAR(64)'),
('zscore_all      DOUBLE'),
('PRIMARY KEY (hugo_symbol'),
('INDEX idx_sample (sample_id)'),
('INDEX idx_gene   (hugo_symbol)'),
(');'),
('-- 6. MRNA ZSCORE — diploid samples'),
('CREATE TABLE mrna_zscore_diploid ('),
('hugo_symbol     VARCHAR(64)'),
('entrez_gene_id  BIGINT'),
('sample_id       VARCHAR(64)'),
('zscore_diploid  DOUBLE'),
('PRIMARY KEY (hugo_symbol'),
('INDEX idx_sample (sample_id)'),
('INDEX idx_gene   (hugo_symbol)'),
(');'),
('-- 7. MRNA ZSCORE — normal reference'),
('CREATE TABLE mrna_zscore_normal ('),
('hugo_symbol     VARCHAR(64)'),
('entrez_gene_id  BIGINT'),
('sample_id       VARCHAR(64)'),
('zscore_normal   DOUBLE'),
('PRIMARY KEY (hugo_symbol'),
('INDEX idx_sample (sample_id)'),
('INDEX idx_gene   (hugo_symbol)'),
(');'),
('-- 8. MUTATION'),
('CREATE TABLE mutation ('),
('tumor_sample_barcode    VARCHAR(64)'),
('hugo_symbol             VARCHAR(64)'),
('entrez_gene_id          BIGINT'),
('start_position          BIGINT'),
('end_position            BIGINT'),
('chromosome              VARCHAR(8)'),
('strand                  VARCHAR(4)'),
('ncbi_build              VARCHAR(16)'),
('variant_classification  VARCHAR(64)'),
('variant_type            VARCHAR(16)'),
('consequence             VARCHAR(128)'),
('reference_allele        VARCHAR(512)'),
('tumor_seq_allele1       VARCHAR(512)'),
('tumor_seq_allele2       VARCHAR(512)'),
('hgvsc                   VARCHAR(256)'),
('hgvsp                   VARCHAR(256)'),
('hgvsp_short             VARCHAR(64)'),
('transcript_id           VARCHAR(32)'),
('t_ref_count             INT'),
('t_alt_count             INT'),
('t_depth                 INT'),
('n_ref_count             INT'),
('n_alt_count             INT'),
('mutation_status         VARCHAR(32)'),
('validation_status       VARCHAR(32)'),
('impact                  VARCHAR(16)'),
('polyphen                VARCHAR(64)'),
('sift                    VARCHAR(64)'),
('hotspot                 TINYINT'),
('ncallers                INT'),
('dbsnp_rs                VARCHAR(32)'),
('cosmic                  VARCHAR(256)'),
('exac_af                 DOUBLE'),
('clin_sig                VARCHAR(128)'),
('center                  VARCHAR(64)'),
('annotation_status       VARCHAR(32)'),
('PRIMARY KEY (tumor_sample_barcode'),
('INDEX idx_gene   (hugo_symbol)'),
('INDEX idx_sample (tumor_sample_barcode)'),
(');'),
('-- 9. COPY NUMBER'),
('CREATE TABLE copy_number ('),
('hugo_symbol       VARCHAR(64)'),
('entrez_gene_id    BIGINT'),
('sample_id         VARCHAR(64)'),
('alteration        TINYINT'),
('alteration_label  VARCHAR(32)'),
('PRIMARY KEY (hugo_symbol'),
('INDEX idx_sample (sample_id)'),
('INDEX idx_gene   (hugo_symbol)'),
(');'),
('-- 10. METHYLATION'),
('CREATE TABLE methylation ('),
('hugo_symbol     VARCHAR(64)'),
('entrez_gene_id  BIGINT'),
('sample_id       VARCHAR(64)'),
('beta_value      DOUBLE'),
('PRIMARY KEY (hugo_symbol'),
('INDEX idx_sample (sample_id)'),
('INDEX idx_gene   (hugo_symbol)'),
(');');
